# Generated by Django 5.2.6 on 2026-03-29 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'reparo_cliente',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Técnico')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'reparo_tecnico',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CELULAR', 'Celular'), ('TABLET', 'Tablet'), ('NOTEBOOK', 'Notebook'), ('CAMERA', 'Câmera'), ('TV', 'Televisor'), ('SOM', 'Aparelho de Som'), ('MICROONDAS', 'Microondas'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Tipo')),
                ('marca', models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('LG', 'LG'), ('SONY', 'Sony'), ('MOTOROLA', 'Motorola'), ('ASUS', 'Asus'), ('ACER', 'Acer'), ('DELL', 'Dell'), ('HP', 'HP'), ('LENOVO', 'Lenovo'), ('OUTRAS', 'Outras marcas')], max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serial', models.CharField(max_length=100, verbose_name='Número de série')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgo_app.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'reparo_equipamento',
            },
        ),
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id_reparo', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('descricao_defeito', models.TextField(verbose_name='Descrição do Defeito')),
                ('descricao_reparo', models.TextField(verbose_name='Descrição do Reparo')),
                ('pecas_substituidas', models.TextField(blank=True, verbose_name='Peças Substituídas')),
                ('custo_reparo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo do Reparo')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgo_app.equipamento', verbose_name='Equipamento')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgo_app.tecnico', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Reparo',
                'verbose_name_plural': 'Reparos',
                'db_table': 'reparo_reparo',
            },
        ),
    ]
